=== vojtn/mff_notes/nprg036/06/tutorial.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="contracts">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="1">
                <xs:element name="contract">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="uri" type="xs:anyURI" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="publishTime" type="xs:dateTime" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="content" type="xs:string" minOccurs="1" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== vojtn/mff_notes/nprg036/06/tutorial.xml
<?xml version="1.0" encoding="UTF-8"?>
<contracts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="tutorial.xsd">
    <contract>
        <uri>https://smlouvy.gov.cz/smlouva/1153037</uri>
        <publishTime>2017-02-01T00:13:13+01:00</publishTime>
        <content>
            
        </content>
    </contract>
    <contract>
        <uri>https://smlouvy.gov.cz/smlouva/1153341</uri>
        <publishTime>2017-02-01T07:33:14+01:00</publishTime>
        <content>
      
        </content>
    </contract>
</contracts>
